---
title: "Get Started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
link <- function(text, url) {
  return(
    paste0(
      "[", text, "]",
      "(", url, ")"
    )
  )
}
dyn_link <- function(text,
                     base_url,
                     relative_url = "",
                     # Change to TRUE when admiral adopts multiversion docs
                     is_multiversion = FALSE,
                     multiversion_default_ref = "main") {
  url <- paste(base_url, relative_url, sep = "/")
  if (is_multiversion) {
    url <- paste(
      base_url,
      Sys.getenv("BRANCH_NAME", multiversion_default_ref),
      relative_url,
      sep = "/"
    )
  }
  return(link(text, url))
}
# Other variables
admiral_homepage <- "https://pharmaverse.github.io/admiral/cran-release"
```

# Introduction

As this is a package extension, if you are new to `{admiral}` then the best place to first start
reading would be this `r dyn_link("Get Started", admiral_homepage, "articles/admiral.html")`
guide. This extension package follows the same main idea and conventions, and re-uses many
functions from `{admiral}`, so it is important to thoroughly understand these to be able to
use `{admiralophtha}`.

# Derivations

The most important functions in `{admiralophtha}` are the
[derivations](../reference/index.html). Again these follow the same
conventions as `{admiral}` but are focused to ophthalmology-specific needs.

# Starting a Script

For the ophthalmology ADaM data structures, an overview of the flow and example function calls
for the most common steps are provided by the following vignettes:

- [Creating ADBCVA](adbcva.html)
- [Creating ADOE](adoe.html)
- [Creating ADVFQ](advfq.html)

# Support

Support is provided via the [admiral Slack
channel](https://app.slack.com/client/T028PB489D3/C02M8KN8269).

<!-- This article is in the process of being written. Please use the `{admiralonco}` "Get Started"  -->
<!-- page (commented out at the moment) as a basis. -->

<!-- # Derivations -->

<!-- The most important functions in `{admiralonco}` are the -->
<!-- [derivations](../reference/index.html#section-derivations). Again these follow the same -->
<!-- conventions as `{admiral}` but are focused to oncology-specific needs. -->

<!-- # Starting a Script -->

<!-- For the oncology ADaM data structures, an overview of the flow and example function calls -->
<!-- for the most common steps are provided by the following vignettes: -->

<!-- - [Creating ADRS](adrs.html) -->
<!-- - [Creating ADTTE](adtte.html) -->

<!-- `{admiralonco}` also provides template R scripts as a starting point. They can be -->
<!-- created by calling `use_ad_template()` from {admiral}, e.g., -->

<!-- ```{r} -->
<!-- library(admiral) -->
<!-- ``` -->

<!-- there used to be some code calling `use_ad_template here (see corresponding admiralonco file) -->
<!-- but it was removed as commenting it out errored the file for some reason. Upond development,  -->
<!-- feel free to locate the code again and paste it in in order to modify it. -->

<!-- A list of all available templates can be obtained by `list_all_templates()` -->
<!-- from {admiral}: -->

<!-- ```{r} -->
<!-- list_all_templates(package = "admiralonco") -->
<!-- ``` -->

<!-- # Support -->

<!-- Support is provided via the [admiral Slack -->
<!-- channel](https://app.slack.com/client/T028PB489D3/C02M8KN8269). -->
